-- DELETE FROM NationRevenueByStream
-- DROP TABLE NationRevenueByStream

-- CREATE TABLE [dbo].[NationRevenueByStream] (
--     [Id]              INT IDENTITY (1, 1) NOT NULL,
--     [NationId]        INT NOT NULL,
--     [Season]          INT NOT NULL,
--     [RevenueStreamId] INT NOT NULL,
--     [TotalRevenue]    INT NOT NULL,
--     CONSTRAINT [PK_NationRevenueByStream] PRIMARY KEY CLUSTERED ([Id] ASC)
-- );